version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-webapp
    ports:
    - "80:80"
    links:
    - redis
    volumes:
    - ./samples:/mnt/samples
  daemon:
    build:
      context: .
      dockerfile: Dockerfile-daemon
    links:
    - redis
    - ursadb
    volumes:
    - ./samples:/mnt/samples
  ursadb:
    build:
      context: ursadb/
      dockerfile: Dockerfile
    volumes:
    - ./samples:/mnt/samples
  ursadb-cli:
    build:
      context: ursadb-cli/
      dockerfile: Dockerfile
    volumes:
    - ./samples:/mnt/samples
    command: tcp://ursadb:9281 --cmd "ping;"
  redis:
    image: redis
