apiVersion: v1
kind: PersistentVolume
metadata:
  name: mquery-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs-server.local
    path: "/opt/nfs"
    readOnly: true
